### ISSUE TITLE
Learning how to talk

### ISSUE THREAD

**Issue by LilSavageJ** [elhadjx/Personal-Budget#1]
Hello I'm lil savage . I am really trying to learn all this with this WORLD IN TODAY Society ! I know it's coming to where this is how we are going to have to talk if we want to be able to talk to one another. Just wait and see! So that being said please think and take into consideration what I am asking from you??there are videos I have watch there are a lot of things I have read! There is a lot a lot to take in! I am asking with everything I have in me saying this from the bottom of my heart. Asking you will you lease mentor me and take me under your wig and not do it for me or show me but explain to me let me do the work with what ever it is and let me learn what you have to learn if you would be interested I don't have any money but I know you will benefit in the future from me!!!

**Comment by elhadjx** [comment]
check [Codecademy](https://www.codecademy.com/)
